# -*- mode: ruby -*-
# vi: set ft=ruby :
# You can ask for more memory and cores when creating your Vagrant machine by
# setting these environment variables (if using VirtualBox):
#   LUMC_VAGRANT_MEMORY=1536 LUMC_VAGRANT_CORES=2 vagrant up
MEMORY = ENV['LUMC_VAGRANT_MEMORY'] || '1024'
CORES = ENV['LUMC_VAGRANT_CORES'] || '1'

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Built using https://git.lumc.nl/m.vermaat.hg/vagrant-debian-jessie-64
  config.vm.box = "debian-jessie-64"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "https://barmsijs.lumc.nl/HG/mvermaat/vagrant/debian-jessie-64.box"
  config.vm.box_download_insecure = true

  # We don't need a shared folder.
  config.vm.synced_folder ".", "/vagrant", :disabled => true

  # Set VM hostname.
  config.vm.hostname = "lumc-vagrant"

  # Accessing "localhost:8090" will access port 80 on the guest machine,
  # likewise for "localhost:8091" and 443.
  config.vm.network :forwarded_port, guest: 80, host: 8090
  config.vm.network :forwarded_port, guest: 443, host: 8091

  # Also override the default SSH port forward.
  config.vm.network :forwarded_port, guest: 22, host: 2523, auto_correct: false, id: "ssh"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :private_network, ip: "192.168.111.223"

  # Provision using our Ansible playbook.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../playbook.yml"
    ansible.inventory_path = "inventory.yml"
    ansible.host_key_checking = false
  end

  config.ssh.insert_key = false

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network :public_network

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  # config.ssh.forward_agent = true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider :virtualbox do |vb|
    # Don't boot with headless mode
    #vb.gui = true

    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", MEMORY.to_i]
    vb.customize ["modifyvm", :id, "--cpus", CORES.to_i]
  end

  # View the documentation for the provider you're using for more
  # information on available options.
end
