---
ansible_host: 127.0.0.1
ansible_port: "{{ lookup('env', 'BASE_SERVER_PORT_FORWARD_SSH') | default(2523, true) }}"
ansible_user: vagrant
ansible_become: true
ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
