---
- hosts: all
  become: true
  vars:
    doc_root: /var/www/example
  tasks:
    - name: Update the Apt package manager database. 
      apt: update_cache=yes

    - name: Install Apache2 via Apt. 
      apt: name=apache2 state=latest

    - name: Create a custom root web directory, with correct group ownership.
      file: path={{ doc_root }} state=directory owner=www-data group=www-data

    - name: Create the index.html test file, with correct group ownership and permissions.  
      copy: src=index.html dest={{ doc_root }}/index.html owner=www-data group=www-data mode=0644

    - name: Create the default Apache virtual host file from template. 
      template: src=vhost.tpl dest=/etc/apache2/sites-available/000-default.conf
      notify: restart apache

 handlers:
    - name: restart apache 
      service: name=apache2 state=restarted
