---
- name: add provisioned user accounts defined in defaults config 
  user: name={{ item.name }} home=/home/{{ item.name }} shell=/bin/bash state=present password={{ item.encrypted_password }}
  with_items: "{{ provisioned_users }}"

- name: add provisioned users to sudo group
  user: name={{ item.name }} groups=sudo append=yes
  with_items: "{{ provisioned_users }}"
  when: item.sudo

- name: add provisioned users to admin group
  user: name={{ item.name }} groups=adm append=yes
  with_items: "{{ provisioned_users }}"
  when: item.adm
